### ISSUE TITLE
Not found Pages

### ISSUE THREAD

**Issue by juanisierra** [Psychedelic/nft-marketplace-fe#484]
### Description
When entering a non-existant NFT id or collection id as query param, a not found page must be showed
### Acceptance Criteria
- [x] When the NFTId query param in the URL is not valid, a not found page must be displayed
- [x] When the collectionId query param in the URL is not valid, a not found page must be displayed

**Comment by prasanthLalapeta** [comment]
PR merged - https://github.com/Psychedelic/nft-marketplace-fe/pull/483
