### ISSUE TITLE
[ICNS] Change Sale for Purchase

### ISSUE THREAD

**Issue by prasanthLalapeta** [Psychedelic/nft-marketplace-fe#646]
![Image](https://user-images.githubusercontent.com/11819091/196984779-266a8f03-4827-466d-bfc6-8de895ffa4b8.png)

instead of complete the "sale" It should say "purchase"

**Comment by prasanthLalapeta** [comment]
Fixed in PR - https://github.com/Psychedelic/nft-marketplace-fe/pull/647

**Comment by karlamiesesfleek** [comment]
### 🚀 QA Testing Notes
> ✔ passes testing

**Comment by karlamiesesfleek** [comment]
### 🚀 QA Testing Notes
> ✔ passes testing
